# Generated by Django 4.2.19 on 2026-03-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vaccination_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vaccinations',
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('distemper', 'Distemper'), ('parvovirus', 'Parvovirus'), ('hepatitis', 'Hepatitis'), ('leptospirosis', 'Leptospirosis'), ('kennel_cough', 'Kennel Cough'), ('rabies', 'Rabies')], max_length=50)),
                ('date_given', models.DateField()),
                ('next_due', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
