# Generated by Django 4.2.19 on 2025-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_featured_image_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='additional_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
