# Generated by Django 4.2.19 on 2025-07-18 09:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_additional_images_delete_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
