# Generated by Django 4.2.19 on 2026-02-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_image_alter_recipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='num_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
